### ISSUE TITLE
suggest refactor to nullobject

### ISSUE THREAD

**Issue by alessandrosoro-QUT** [QUT-CAB302-Software-Development/android-application-project#7]
I think the null  return value may lead to errors, how about refactoring to NullObject instead?
https://github.com/QUT-CAB302-Software-Development/android-application-project/blob/master/app/src/main/java/example/data/StaticUserDAO.java#L28

**Comment by dangkhuongtran** [comment]
Is the NullObject a default object, for example a User named Guest?

**Comment by alessandrosoro-QUT** [comment]
Yes, better to extend the User class (e.g. NullUser, or DefaultUser) and put the default behaviour in it, so you don't have to test for null all the time.
